SRCS = main.cpp

OBJS = ${SRCS:.cpp=.o}

CC = c++

CFLAGS = -Wall -Wextra -Werror

OPT_FLAG = -std=c++98 -g

RM = rm -f

test = replace

${test}:	${OBJS}
			${CC} ${CFLAGS} ${SRCS} -o ${test}

all:	${test}

clean:	
		${RM} ${OBJS}

fclean:	clean
		${RM} ${test}

re:		fclean all

.phony:	fclean all clean re
 #
sfffffffffffffffff
 